### ISSUE TITLE
Missing Export/Import item 

### ISSUE THREAD

**Issue by mikhoul** [ChoGGi/Stylish-Custom#2]
Where is the Export/Import styles item in the dropdown menu ?   

http://i.imgur.com/21mxSez.png

Regards :octocat:

**Comment by ChoGGi** [comment]
The defaults were changed around , just goto Options>Menu items>Ex/Import menuitem location and change it to Stylish

**Comment by mikhoul** [comment]
Thanks a lot ! 👍
