### ISSUE TITLE
Error new version!

### ISSUE THREAD

**Issue by vanja-san** [ChoGGi/Stylish-Custom#3]
## After the update, I now get this error:

![Screenshot](https://github.com/vanja-san/Screenshots/blob/master/Screenshot/2017-06-24_03-57-49.png)

```
XML parsing error: error handling external entity reference
Address: chrome://stylish-custom/content/options.xul
Line 10, symbol 3:

   %optionsDTD;
-- ^
```

**Comment by ChoGGi** [comment]
You missed a " in options.dtd
<!ENTITY SaveMenu "Меню сохранения>

:( I already sent 0.9.0 to AMO, as it had some other stuff I wanted to add. Whenever it gets approved (...) I'll upload again.

Edit: Queue Position: 52 of 122 (I uploaded it on the 19 at position 100, so it shouldn't take too long)

**Comment by ChoGGi** [comment]
v0.9.0 is up on AMO/added the signed XPI to the release on here
https://addons.mozilla.org/addon/stylish-custom/
